const { ethers } = require("ethers");
const path = require("path");
const fs = require("fs");

// Path to your contract JSON artifact (generated by hardhat compile)
const contractJsonPath = path.join(
  __dirname,
  "..",
  "contracts",
  "TestamentRegistry.json",
);

// Cache the contract config to avoid reading file multiple times
let cachedContractConfig = null;

function loadContractConfig() {
  if (cachedContractConfig) return cachedContractConfig;

  try {
    const raw = fs.readFileSync(contractJsonPath, "utf-8");
    const parsed = JSON.parse(raw);
    cachedContractConfig = {
      address: process.env.CONTRACT_ADDRESS || parsed.address,
      abi: parsed.abi,
    };
    console.log("✅ Contract config loaded from:", contractJsonPath);
    return cachedContractConfig;
  } catch (error) {
    console.error("❌ Failed to load contract config:", error.message);
    // Fallback to env variables if JSON not found
    return {
      address: process.env.CONTRACT_ADDRESS,
      abi: null, // Will need to define ABI manually
    };
  }
}

// Get contract instance (read-only)
function getContractReadOnly() {
  const config = loadContractConfig();
  if (!config.address) {
    throw new Error("Contract address not configured");
  }
  const provider = new ethers.JsonRpcProvider(process.env.SEPOLIA_RPC_URL);
  return new ethers.Contract(config.address, config.abi, provider);
}

// Get contract instance with signer (for transactions)
function getContractWithSigner(privateKey) {
  const config = loadContractConfig();
  if (!config.address) {
    throw new Error("Contract address not configured");
  }
  const provider = new ethers.JsonRpcProvider(process.env.SEPOLIA_RPC_URL);
  const wallet = new ethers.Wallet(privateKey, provider);
  return new ethers.Contract(config.address, config.abi, wallet);
}

// ============ TESTAMENT FUNCTIONS (Your existing ones) ============

async function getTestament(id) {
  try {
    const contract = getContractReadOnly();
    const testament = await contract.testaments(id);
    return {
      id: testament.id,
      testator: testament.testator,
      notary: testament.notary,
      ipfsHash: testament.ipfsHash,
      timestamp: testament.timestamp,
      isValidated: testament.isValidated,
    };
  } catch (error) {
    console.error(`Error fetching testament ${id}:`, error.message);
    return null;
  }
}

async function getTestatorTestaments(address) {
  try {
    const contract = getContractReadOnly();
    const testaments = await contract.getTestatorTestaments(address);
    return testaments.map((t) => ({
      id: t.id,
      testator: t.testator,
      notary: t.notary,
      ipfsHash: t.ipfsHash,
      timestamp: t.timestamp,
      isValidated: t.isValidated,
    }));
  } catch (error) {
    console.error(`Error fetching testaments for ${address}:`, error.message);
    return [];
  }
}

// ============ NOTARY FUNCTIONS (For your inactivity monitor) ============

async function getNotaryInfo(walletAddress) {
  try {
    const contract = getContractReadOnly();
    const notary = await contract.notaries(walletAddress);
    return {
      walletAddress: notary.walletAddress,
      name: notary.name,
      publicKey: notary.publicKey,
      isActive: notary.isActive,
      isAlive: notary.isAlive,
      keyBackupNotary: notary.keyBackupNotary,
      lastActive: notary.lastActive.toString(),
    };
  } catch (error) {
    console.error(
      `Error fetching notary info for ${walletAddress}:`,
      error.message,
    );
    return null;
  }
}

async function deactivateNotary(walletAddress, adminPrivateKey) {
  try {
    const contract = getContractWithSigner(adminPrivateKey);
    const tx = await contract.deactivateNotary(walletAddress);
    const receipt = await tx.wait();
    console.log(
      `✅ Deactivated ${walletAddress} on-chain. Tx: ${receipt.hash}`,
    );
    return { success: true, txHash: receipt.hash };
  } catch (error) {
    console.error(`❌ Failed to deactivate ${walletAddress}:`, error.message);
    return { success: false, error: error.message };
  }
}

async function notaryPing(walletAddress, privateKey) {
  try {
    const contract = getContractWithSigner(privateKey);
    const tx = await contract.notaryPing();
    const receipt = await tx.wait();
    console.log(`✅ Notary ${walletAddress} pinged. Tx: ${receipt.hash}`);
    return { success: true, txHash: receipt.hash };
  } catch (error) {
    console.error(`❌ Failed to ping for ${walletAddress}:`, error.message);
    return { success: false, error: error.message };
  }
}

// Get current block timestamp
async function getCurrentBlockTimestamp() {
  try {
    const provider = new ethers.JsonRpcProvider(process.env.SEPOLIA_RPC_URL);
    const block = await provider.getBlock("latest");
    return block.timestamp;
  } catch (error) {
    console.error("Error getting block timestamp:", error.message);
    return Math.floor(Date.now() / 1000); // Fallback to system time
  }
}

// Calculate days inactive
function calculateDaysInactive(lastActiveTimestamp, currentTimestamp) {
  const lastActive = parseInt(lastActiveTimestamp);
  const current = parseInt(currentTimestamp);
  const secondsInactive = current - lastActive;
  return Math.floor(secondsInactive / (24 * 60 * 60));
}

// Get all active notaries (requires a list of addresses from your database)
async function getActiveNotaryStatuses(notaryAddresses) {
  const results = [];
  for (const address of notaryAddresses) {
    const info = await getNotaryInfo(address);
    if (info && info.isActive) {
      results.push({ address, ...info });
    }
  }
  return results;
}

// Health check
async function healthCheck() {
  try {
    const provider = new ethers.JsonRpcProvider(process.env.SEPOLIA_RPC_URL);
    const blockNumber = await provider.getBlockNumber();
    const config = loadContractConfig();
    const contractCode = await provider.getCode(config.address);

    return {
      connected: true,
      blockNumber,
      contractDeployed: contractCode !== "0x",
      contractAddress: config.address,
      rpcUrl: process.env.SEPOLIA_RPC_URL,
    };
  } catch (error) {
    return {
      connected: false,
      error: error.message,
    };
  }
}

module.exports = {
  // Testament functions (existing)
  getTestament,
  getTestatorTestaments,
  // Notary functions (new)
  getNotaryInfo,
  deactivateNotary,
  notaryPing,
  getCurrentBlockTimestamp,
  calculateDaysInactive,
  getActiveNotaryStatuses,
  healthCheck,
  // Utility
  getContractReadOnly,
  getContractWithSigner,
};
